webtalk_init -webtalk_dir C:\\Users\\MENGXIAN\\Desktop\\sdk_arduino_IKS01A1\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期一 十月 24 16:47:50 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "mt16hjk57trtcfp60fnsdj4mh3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.1_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1477272694988" -context "sdk\\\\hardware/1477272694988"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1477272694988"
webtalk_add_data -client sdk -key Processors -value "5" -context "sdk\\\\hardware/1477272694988"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.1_AR67511" -context "sdk\\\\hardware/1477272694988"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1477272694988"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1477272694988"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1477272694988"
webtalk_add_data -client sdk -key uid -value "1477272754876" -context "sdk\\\\bsp/1477272754876"
webtalk_add_data -client sdk -key hwid -value "1477272694988" -context "sdk\\\\bsp/1477272754876"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1477272754876"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1477272754876"
webtalk_add_data -client sdk -key uid -value "1477272776177" -context "sdk\\\\application/1477272776177"
webtalk_add_data -client sdk -key hwid -value "1477272694988" -context "sdk\\\\application/1477272776177"
webtalk_add_data -client sdk -key bspid -value "1477272754876" -context "sdk\\\\application/1477272776177"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1477272776177"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1477272776177"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1477272776177"
webtalk_transmit -clientid 2357529548 -regid "" -xml C:\\Users\\MENGXIAN\\Desktop\\sdk_arduino_IKS01A1\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\MENGXIAN\\Desktop\\sdk_arduino_IKS01A1\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\MENGXIAN\\Desktop\\sdk_arduino_IKS01A1\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
