
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 5.4
 PARAMETER PROC_INSTANCE = iop3_mb
 PARAMETER stdin = iop3_mb3_uartlite_d1_d0
 PARAMETER stdout = iop3_mb3_uartlite_d1_d0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.4
 PARAMETER HW_INSTANCE = iop3_mb
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = arduino_io_switch
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = iop3_arduino_io_switch_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = iop3_mb3_gpio_subsystem_mb3_gpio_pl_sw_a5_a0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = iop3_mb3_gpio_subsystem_mb3_gpio_pl_sw_d13_d2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = iop3_mb3_gpio_subsystem_mb3_gpio_pl_sw_d1_d0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iic
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = iop3_mb3_iic_subsystem_mb3_iic_pl_sw
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iic
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = iop3_mb3_iic_subsystem_mb3_shared_iic_sw
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 3.5
 PARAMETER HW_INSTANCE = iop3_mb3_intc
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = iop3_mb3_lmb_lmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 4.2
 PARAMETER HW_INSTANCE = iop3_mb3_spi_subsystem_mb3_spi_pl_sw
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 4.2
 PARAMETER HW_INSTANCE = iop3_mb3_spi_subsystem_mb3_spi_pl_sw_d13_d10
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = iop3_mb3_timers_subsystem_mb3_timer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = iop3_mb3_timers_subsystem_mb3_timer_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = iop3_mb3_timers_subsystem_mb3_timer_2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = iop3_mb3_timers_subsystem_mb3_timer_3
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = iop3_mb3_timers_subsystem_mb3_timer_4
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = iop3_mb3_timers_subsystem_mb3_timer_5
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = iop3_mb3_uartlite_d1_d0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = sysmon
 PARAMETER DRIVER_VER = 7.2
 PARAMETER HW_INSTANCE = iop3_mb3_xadc
END


